### ISSUE TITLE
"[an error occurred while processing this directive]" on Moodle 2.5

### ISSUE THREAD

**Issue by joeythibault** [DBezemer/moodle-report_mygrades#1]
I have a dedicated virtual server from Bluehost, installed for Moodle 2.5 this morning with the latest version posted (for 2.5) on Moodle.org but receive the following error anytime I try to access the report.

[an error occurred while processing this directive]

Any thoughts?

**Comment by DBezemer** [comment]
This plugin is no longer maintained.
